import { useState } from 'react';
import { Activity, ArrowLeft, Crown, LogOut, Menu, ShieldCheck, Users, Building2 } from 'lucide-react';
import type { UserRole } from '../../types';
import { AdminPanel } from './AdminPanel';

export function SuperAdminPortal({ user, onExit, onLogout }: { user: { id: string; name: string; email: string; role: UserRole } | null; onExit: () => void; onLogout: () => void }) {
  const [menuOpen, setMenuOpen] = useState(false);
  return <div className="min-h-screen bg-[#070A12] text-white"><header className="sticky top-0 z-50 border-b border-cyan-400/15 bg-[#0B1020]/95 backdrop-blur-xl"><div className="max-w-[1600px] mx-auto px-4 sm:px-7 h-18 flex items-center justify-between gap-4"><div className="flex items-center gap-3"><div className="w-10 h-10 rounded-xl flex items-center justify-center bg-gradient-to-br from-cyan-400 to-violet-600"><Crown className="w-5 h-5" /></div><div><p className="font-black tracking-tight">FIRE STONE <span className="text-cyan-300">CONTROL</span></p><p className="text-[10px] text-slate-400 uppercase tracking-widest">Portail Super Admin</p></div></div><nav className="hidden md:flex items-center gap-5 text-xs font-bold text-slate-300"><span className="flex items-center gap-1.5 text-cyan-200"><Activity className="w-3.5 h-3.5" /> Supervision globale</span><span className="flex items-center gap-1.5"><Building2 className="w-3.5 h-3.5" /> Tous les clubs</span><span className="flex items-center gap-1.5"><Users className="w-3.5 h-3.5" /> Utilisateurs & sécurité</span></nav><div className="flex items-center gap-2"><div className="hidden sm:block text-right mr-2"><p className="text-xs font-bold">{user?.name}</p><p className="text-[10px] text-cyan-300">SUPER_ADMIN</p></div><button onClick={onExit} title="Voir le portail public" className="p-2 rounded-lg text-slate-400 hover:text-white hover:bg-white/5"><ArrowLeft className="w-4 h-4" /></button><button onClick={onLogout} title="Se déconnecter" className="p-2 rounded-lg text-red-300 hover:text-red-100 hover:bg-red-500/10"><LogOut className="w-4 h-4" /></button><button onClick={() => setMenuOpen(!menuOpen)} className="md:hidden p-2 rounded-lg bg-white/5"><Menu className="w-4 h-4" /></button></div></div>{menuOpen && <div className="md:hidden px-5 pb-4 flex flex-col gap-2 text-xs text-slate-300"><span>Supervision globale</span><span>Tous les clubs et demandes</span><span>Utilisateurs et sécurité</span></div>}</header><main className="max-w-[1600px] mx-auto px-4 sm:px-7 py-7"><div className="mb-6 rounded-2xl border border-cyan-400/15 bg-cyan-400/5 px-4 py-3 text-xs text-slate-300 flex gap-2"><ShieldCheck className="w-4 h-4 text-cyan-300 shrink-0" /> Vous êtes dans la console plateforme. Elle est indépendante des espaces clubs et donne une vision transversale de toutes les données.</div><AdminPanel currentRole="SUPER_ADMIN" authUser={user} /></main></div>;
}
